# Copyright 2026 OpenSynergy Indonesia
# Copyright 2026 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "Donation",
    "version": "14.0.1.1.0",
    "website": "https://simetri-sinergi.id",
    "author": "PT. Simetri Sinergi Indonesia, OpenSynergy Indonesia",
    "contributors": [
        "Andhitia Rama <andhitia.r@gmail.com>",
    ],
    "license": "AGPL-3",
    "installable": True,
    "application": True,
    "depends": [
        "ssi_master_data_mixin",
        "ssi_financial_accounting",
        "ssi_company_currency_mixin",
        "ssi_res_partner_m2o_configurator_mixin",
        "ssi_accounting_entry_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_cancel_mixin",
        "web_tour",
    ],
    "data": [
        "security/ir_module_category_data.xml",
        "security/ir_module_category/donation.xml",
        "security/res_groups/donation_fund.xml",
        "security/res_groups/donation_type.xml",
        "security/res_groups/donation.xml",
        "security/ir_model_access/donation_fund.xml",
        "security/ir_model_access/donation_type.xml",
        "security/ir_model_access/donation.xml",
        "security/ir_rule/donation.xml",
        "ir_sequence/donation_fund.xml",
        "ir_sequence/donation_type.xml",
        "ir_sequence/donation.xml",
        "sequence_template/donation_fund.xml",
        "sequence_template/donation_type.xml",
        "sequence_template/donation.xml",
        "approval_template/donation.xml",
        "policy_template/donation.xml",
        "menu.xml",
        "views/donation_fund.xml",
        "views/donation_type.xml",
        "views/donation.xml",
        "views/assets.xml",
    ],
}
